# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: ^(.idea/|test-data/1.1/simple/.*\.json$|test-data/1.1/missing_resource/.*\.json$)
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      #- id: check-symlinks
      #- id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      name: "Format code"
      language_version: python3
      files: swaggerpy/

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: [--settings-path=pyproject.toml]
      files: swaggerpy/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
      args:
        - --follow-imports=normal
        - --install-types
        - --non-interactive
      additional_dependencies:
        - "loguru==0.6.0"
      files: swaggerpy/

  - repo: "https://github.com/asottile/blacken-docs"
    rev: "v1.12.1"
    hooks:
      - id: "blacken-docs"
        name: "Format docs (blacken-docs)"
        args: ["-l", "64"]
        additional_dependencies:
          - "black==22.10.0"

  - repo: https://github.com/PyCQA/doc8
    rev: v1.0.0
    hooks:
      - id: doc8
        #exclude: CHANGELOG\.rst$
        args:
          - '--max-line-length=90'

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
        #exclude: CHANGELOG\.rst$
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/myint/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        files: swaggerpy/
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
        files: swaggerpy/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-ll", "-q", "-r"]
        files: swaggerpy/
