name: Release

on:
  push:
    # release on tag push
    tags:
      - 'v*'

jobs:
  packaging:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      PYTHONIOENCODING: utf-8
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
    - name: Set git crlf/eol
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install tox

    - name: Build dist pkgs
      run: |
        tox -e build

    - name: Upload artifacts
      if: matrix.python-version == 3.7 && runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ./dist/swaggerpy-*

  create_release:
    name: Create Release
    needs: [packaging]
    runs-on: ubuntu-20.04

    steps:
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # download all artifacts to project dir
      - uses: actions/download-artifact@v3

      - name: Generate changes file
        uses: sarnold/gitchangelog-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body_path: CHANGES.md
          draft: false
          prerelease: false
          files: |
            packages/swaggerpy-*

  docs:
    name: Release docs
    needs: [create_release]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Build docs
      run: |
        tox -e docs-lint
        tox -e docs

    - uses: actions/upload-artifact@v3
      with:
        name: ApiDocsHTML
        path: "docs/_build/html/"

    - name: set nojekyll for github
      run: |
        sudo touch docs/_build/html/.nojekyll

    - name: Deploy docs to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/_build/html/
        SINGLE_COMMIT: true

  # When a GitHub release is made, upload the artifacts to PyPI
  upload:
    name: Upload to PyPI
    runs-on: ubuntu-20.04
    needs: [packaging]

    steps:
    - uses: actions/setup-python@v4

    - uses: actions/download-artifact@v3

    - name: check artifacts
      run: find . -maxdepth 2 -name swaggerpy-\* -type f

#    - name: Publish bdist and sdist packages
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        password: ${{ secrets.PYPI_API_TOKEN }}
#        packages_dir: packages/
#        print_hash: true
